# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "tr ouwens"
subtitle: "jqno.nl"
name: "Jan Ouwens"
description: "By the way: things I want to say"
search: true

author:
  name: "Jan Ouwens"
  avatar: "https://www.gravatar.com/avatar/f2e0574e5b5e770b5c5678b91ba889a6"
  bio: "<a href='/about'>Scala by day, Java by night</a>"
  location: "The Netherlands"
  github: jqno
  stackoverflow: 127863
  twitter: jqno

footer:
  links:
    - label: "Privacy policy"
      url: "/privacy"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "side"
      share: false
      related: false
  - scope:
      type: posts
    values:
      permalink: /:year/:month/:day/:title/
      read_time: true
      sidebar:
        nav: "side"
      show_date: true
      comments: true
  - scope:
      type: pages
    values:
      read_time: false
      comments: false
      sidebar:
        nav: "side"

tag_archive:
  type: liquid
  path: /tags/

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.20.2
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Reading files
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]
